package server;

import commons.Activity;
import commons.ClientMessage;
import commons.Game;
import commons.Player;
import commons.Question;
import commons.ServerMessage;
import org.springframework.messaging.MessagingException;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import server.api.ActivityController;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Controller
@RequestMapping("/")
public class MainMessageController {

    private SimpMessagingTemplate simpMessagingTemplate;
    private ActivityController activityController;
    private HashMap<String, Game> games;

    public MainMessageController(SimpMessagingTemplate simpMessagingTemplate, ActivityController activityController) {
        this.simpMessagingTemplate = simpMessagingTemplate;
        this.activityController = activityController;

        games = new HashMap<>();
    }

    @MessageMapping("/general")
    public void handleClientMessages(ClientMessage msg){
        ServerMessage result = null;

        try{
            switch(msg.type){
                case INIT_MULTIPLAYER:
                    // do something
                    break;
                case INIT_SINGLEPLAYER:
                    // first init the game
                    var initMsg = initSingleplayerGame(msg);
                    if(initMsg != null){
                        simpMessagingTemplate.convertAndSend("/topic/client/" + msg.playerID, initMsg);
                        // then send a first question

                        result = nextQuestion(initMsg.score, games.get(initMsg.gameID));
                    }

                    break;
                case TEST:
                    // for testing purposes
                    result = new ServerMessage(ServerMessage.Type.TEST);
                case SUBMIT_SINGLEPLAYER:
                    if(msg.gameID == null || msg.playerID == null) return;

                    // check if specified game and player exist
                    Game g = games.get(msg.gameID);
                    if(g == null) return;
                    Player p = g.getPlayerWithID(msg.playerID);
                    if(p == null) return;

                    // update player's score
                    int scoreForQuestion = 0;
                    if(Objects.equals(msg.chosenActivity, g.getCorrectAnswerID())){
                        scoreForQuestion = 100 + (int)(100 * msg.time);
                    }
                    p.setScore(p.getScore() + scoreForQuestion);

                    // send results msg
                    // TODO: change to send results message (if you answered correctly and your score)
                    // TODO: add some deferred method to send a next question after 3-5 seconds
                    result = nextQuestion(p.getScore(), g);
                    break;
                default:
                    // unknown message
            }

            // if we created a valid message, we send it to a specific client at /client/{ID}
            if(result == null) return;

            simpMessagingTemplate.convertAndSend("/topic/client/" + msg.playerID, result);
        }
        catch(MessagingException ex){
            System.out.println("MessagingException on handleClientMessages: " + ex.getMessage());
        }

    }

    private ServerMessage initSingleplayerGame(ClientMessage msg){
        // 0. Check if player name is correct
        if(msg.playerName == null || msg.playerName.isEmpty()){
            // TODO: send error message
            return null;
        }

        // 1. Create a new game
        Game g = new Game(new ArrayList<>(), UUID.randomUUID().toString());
        g.addPlayer(new Player(msg.playerName, msg.playerID));
        games.put(g.getID(), g);

        // 2. Return a message with the first Question, gameID and an initial score
        ServerMessage result = new ServerMessage(ServerMessage.Type.NEW_SINGLEPLAYER_GAME);
        result.score = 0;
        result.gameID = g.getID();

        return result;
    }

    private ServerMessage nextQuestion(int playerScore, Game forGame){
        ServerMessage result = new ServerMessage(ServerMessage.Type.NEXT_QUESTION);
        // TODO: Question class should be generated by a proper method
        List<Activity> selectedActivities =
                List.of(activityController.getRandom().getBody(),
                        activityController.getRandom().getBody(),
                        activityController.getRandom().getBody());
        result.question = new Question(selectedActivities, Question.Type.COMPARE);
        // TEMPORARY SOLUTION
        Activity max = selectedActivities.get(0);
        for(int i = 1; i < selectedActivities.size(); ++i){
            Activity activity = selectedActivities.get(i);
            if(activity.consumptionInWh > max.consumptionInWh) max = activity;
        }

        // save the correct answer in the Game object

        forGame.setCorrectAnswerID(max.id);

        result.score = playerScore;
        result.timerFull = 10.0; // 10 seconds
        result.timerFraction = 1.0;

        return result;
    }
}
